### ISSUE TITLE
Dead linki do SDK

### ISSUE THREAD

**Issue by vistafan12** [Konnekt/konnekt#1]
Cześć,

ostatnio chciałem się zabawić tym kodem i trafiłem na problem.

Otóż plik SDK nie istnieje na serwerze:
http://www.konnekt.info/sdk-files/lib.zip

Gdzie takowy mogę pobrać?

**Comment by dexterxx-pl** [comment]
A tu: https://github.com/Konnekt/konnekt-sdk ?

**Comment by vistafan12** [comment]
Z tego co pamietam to w tym zipie były inne SDKi.

**Comment by hash** [comment]
6 lat w grobie, ale nostalgia pozostała.

**Comment by vistafan12** [comment]
@hash co prawda to prawda :P

**Comment by vistafan12** [comment]
DUMP, ktoś coś?

**Comment by Sija** [comment]
@panrafal?

**Comment by panrafal** [comment]
Przepraszam, miałem to ogarnąć dawno temu :/ Miło, że ktoś jeszcze pamięta :)

Przywróciłem stronę pod http://konnekt.stamina.pl/, więc SDK jest tu: http://konnekt.stamina.pl/sdk-files/

Żeby nigdy nie zginęło, wrzuciłem też na GH: https://github.com/Konnekt/konnekt/releases/tag/v0.6.23.142

**Comment by panrafal** [comment]
No i powodzenia @vistafan12

**Comment by vistafan12** [comment]
Dzieki, dam znac gdy się uda.
